// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPCUXCbsZcEsCCwoNsblNZEHl-nfpmic',
    appId: '1:81850506677:web:f14dbe72e32fa5892a0dfc',
    messagingSenderId: '81850506677',
    projectId: 'doctorappointment-68f21',
    authDomain: 'doctorappointment-68f21.firebaseapp.com',
    storageBucket: 'doctorappointment-68f21.firebasestorage.app',
    measurementId: 'G-7RK1FPY1VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMHZx7qt-9Aq70Uetiw2jIsiXFMS2-Eo',
    appId: '1:81850506677:android:a87b88c172d351b52a0dfc',
    messagingSenderId: '81850506677',
    projectId: 'doctorappointment-68f21',
    storageBucket: 'doctorappointment-68f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWlgCxCRi9aCg4-xjmObxTh1vk0Bf-0HA',
    appId: '1:81850506677:ios:3b33e36328ede2c72a0dfc',
    messagingSenderId: '81850506677',
    projectId: 'doctorappointment-68f21',
    storageBucket: 'doctorappointment-68f21.firebasestorage.app',
    iosBundleId: 'com.example.doctorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbPCUXCbsZcEsCCwoNsblNZEHl-nfpmic',
    appId: '1:81850506677:web:180d2ceab8bb61cd2a0dfc',
    messagingSenderId: '81850506677',
    projectId: 'doctorappointment-68f21',
    authDomain: 'doctorappointment-68f21.firebaseapp.com',
    storageBucket: 'doctorappointment-68f21.firebasestorage.app',
    measurementId: 'G-V0CRX98MJX',
  );
}
